# Generated by Django 5.0.1 on 2024-04-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_post_author_post_image_post_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
    ]
